name: "GitHub Actions Artifact Cleaner"
author: "Aidan Steele @ Glass Echidna"
description: |
  This is an action that you can run on a regular basis to clean up outdated
  workflow run artifacts before their typical 90 day expiry.

  By default, all artifacts are deleted. There are options to only delete big
  artifacts, artifacts of a certain age or ones with a specific name.

  Suggested usage is in a standalone workflow doc at `.github/workflows/cleanup.yml`
  with the following content:

  ```
  name: clean artifacts

  on:
    schedule:
      - cron: '0 0 * * *'

  jobs:
    clean:
      runs-on: ubuntu-latest
      steps:
        - name: cleanup
          uses: glassechidna/artifact-cleaner@master
          with:
            minimumAge: 86400 # all artifacts at least one day old
  ```

  This cleans all artifacts once a day.
branding:
  icon: trash-2
  color: red

inputs:
  minimumDeletionSize:
    description: >
      Specify a minimum size of artifacts to delete in bytes. Artifacts smaller
      than this won't be deleted.
    required: false
    default: "0"
  name:
    description: >
      (Optional) Specify an artifact name to delete. All other artifacts will
      be left alone - even if match other criteria,
    required: false
  minimumAge:
    description: Only delete artifacts older than this, measured in seconds.
    required: false
    default: "0"
  repository:
    description: ""
    required: false
    default: ${{ github.repository }}
  token:
    description: ""
    required: false
    default: ${{ github.token }}

runs:
  using: docker
  image: Dockerfile
